"""
1000+ Test Questions for Salesforce Chat API (PostgreSQL backend)
Tests the chat endpoint to verify queries run correctly on PostgreSQL.

Run: python tests/test_questions.py
  - Tests all questions, reports pass/fail, shows errors
  - Re-tests failed questions after self-correction attempts

Requires: pip install httpx
"""
import os
import sys
import json
import time
import uuid
import httpx

BASE_URL = os.getenv("TEST_API_URL", "http://localhost:8000")
AUTH_TOKEN = os.getenv("TEST_AUTH_TOKEN", "")

# ═══════════════════════════════════════════════════════════════════════
# QUESTION CATEGORIES
# ═══════════════════════════════════════════════════════════════════════

SIMPLE_STUDENT_QUERIES = [
    "Show all students",
    "List all active students",
    "How many students do we have?",
    "Show students in market",
    "List students who are active in market",
    "Show me students currently in marketing",
    "Get all students with their technology",
    "Show student list with email",
    "List student names and phone numbers",
    "Show all students with their BU name",
    "Get students and their visa status",
    "Show me students with their marketing status",
    "List all students and their technology",
    "Who are the students on bench?",
    "Show me students with verbal confirmation",
    "List confirmed students",
    "Show students on hold",
    "Who got pulled out?",
    "Students not ready for market",
    "Show students with status confirmed",
    "List all active in market students",
    "Get students with H1B visa",
    "Show OPT students",
    "List CPT students",
    "Show all GC holders",
    "Students with citizen status",
    "H4 EAD students list",
    "Show L1 visa students",
    "List students on L2 EAD",
    "Show me Java students",
    "List all Python developers",
    "Who are the .NET students?",
    "Show Salesforce technology students",
    "AWS students list",
    "Azure technology students",
    "DevOps students in market",
    "Data Engineering students",
    "React developers list",
    "Angular students",
    "Full Stack students",
    "SAP technology students",
    "ServiceNow students",
    "Cybersecurity students",
    "AI/ML students",
    "Tableau students list",
    "Power BI students",
    "Selenium testers",
    "Manual testing students",
    "Business Analyst students",
    "Show me all students with days in market",
    "Students in market more than 30 days",
    "Students in market more than 60 days",
    "Students in market more than 90 days",
    "Show students with their recruiter name",
    "List students with offshore manager",
    "Show all students sorted by technology",
    "Students sorted by days in market",
    "Show latest students added",
    "List students by created date",
    "Show students with project started status",
    "Students in pre marketing",
    "Show students with project completed status",
    "List all student technologies",
    "How many students in each technology?",
    "Show students count by visa status",
    "Students with more than 100 days in market",
    "New students added recently",
    "Show students without phone number",
    "Students without email",
    "List students with their batch",
    "Show students sorted by name",
    "Total number of active students",
    "How many students are in verbal confirmation?",
    "Count of students by status",
    "Show STEM OPT students",
    "List USC students",
    "Students with GC visa in Java",
    "H1 students with DevOps technology",
    "OPT students in Data Engineering",
    "Show students with more than 50 days in market",
    "Who has been in market the longest?",
    "Top 10 students by days in market",
    "Show me all active students with Java technology",
    "Python students who are active in market",
    "Active .NET students",
    "DevOps students who are active",
    "List all students under pre marketing status",
    "Show students added this month",
    "Students created last week",
    "New students added last 7 days",
    "Students added in the last 30 days",
    "Show recently modified students",
]

SIMPLE_SUBMISSION_QUERIES = [
    "Show all submissions",
    "List today submissions",
    "Show today's submissions",
    "How many submissions today?",
    "Today submissions count",
    "Show this week submissions",
    "This week's submissions list",
    "Show last week submissions",
    "How many submissions last week?",
    "Show this month submissions",
    "This month submission count",
    "List last month submissions",
    "Show submissions for last 7 days",
    "Last 14 days submissions",
    "Last 30 days submissions",
    "Show all submissions with BU name",
    "List submissions with client name",
    "Show submissions with student name",
    "Get submissions with technology",
    "Show submissions with recruiter",
    "List submissions sorted by date",
    "Latest submissions first",
    "Show recent submissions",
    "Submissions sorted by BU",
    "Show submissions count",
    "How many total submissions?",
    "Show submission status breakdown",
    "List submissions with vendor name",
    "Show submissions with rate",
    "Submissions with rate above 60",
    "Submissions with rate above 80",
    "Show high rate submissions",
    "List submissions with offshore manager",
    "Show submissions with onsite manager",
    "Submissions with prime vendor",
    "Show all submissions this quarter",
    "Last quarter submissions",
    "This year submissions",
    "Show submissions for yesterday",
    "Yesterday's submission list",
]

SIMPLE_INTERVIEW_QUERIES = [
    "Show all interviews",
    "List today interviews",
    "Today's interviews",
    "How many interviews today?",
    "Show this week interviews",
    "This week's interview list",
    "Last week interviews",
    "How many interviews last week?",
    "This month interviews",
    "Show last month interviews",
    "Interviews in last 7 days",
    "Last 14 days interviews",
    "Last 30 days interviews",
    "Show interviews with final status",
    "List interviews by type",
    "Show interview types",
    "List technical interviews",
    "Show client interviews",
    "HR interviews list",
    "Panel interviews",
    "Show first round interviews",
    "Second round interviews",
    "Final round interviews",
    "Show selected interviews",
    "Interviews with confirmation status",
    "Rejected interviews",
    "Rescheduled interviews",
    "Cancelled interviews",
    "Show interviews sorted by date",
    "Latest interviews",
    "Recent interviews",
    "Interviews with good feedback",
    "Very good interviews",
    "Average interviews",
    "Show interviews with student name",
    "List interviews with BU name",
    "Interviews with onsite manager",
    "Show interviews with technology",
    "Interviews with client name",
    "Show all interviews this quarter",
]

SIMPLE_JOB_QUERIES = [
    "Show all jobs",
    "List active jobs",
    "How many jobs are there?",
    "Show jobs with status",
    "List job titles",
    "Show jobs by company",
    "Recent jobs added",
    "Jobs created this month",
    "Jobs created last week",
    "Show jobs with technology",
    "List W2 jobs",
    "Show C2C jobs",
    "PD type jobs",
    "Jobs sorted by date",
    "Latest jobs",
]

SIMPLE_EMPLOYEE_QUERIES = [
    "Show all employees",
    "List active employees",
    "How many employees?",
    "Show employees by department",
    "List employee designations",
    "Show recently added employees",
    "Employees created this month",
    "Employee list with status",
    "Show all employee names",
    "Active employees count",
]

# ── Date-filtered queries ──
DATE_FILTERED_QUERIES = [
    "Today's submissions BU wise",
    "Yesterday submissions by BU",
    "This week submissions count",
    "Last week total submissions",
    "This month submissions breakdown",
    "Last month submissions analysis",
    "Last 3 days submissions",
    "Last 5 days submissions by BU",
    "Last 7 days submissions BU wise",
    "Last 10 days submissions",
    "Last 14 days submissions by BU",
    "Last 20 days submissions",
    "Last 30 days all submissions",
    "Today interviews list",
    "Yesterday interviews",
    "This week interviews by BU",
    "Last week interviews count",
    "This month interview breakdown",
    "Last month interviews analysis",
    "Last 7 days interviews",
    "Last 14 days interviews",
    "Last 30 days interviews",
    "Students added today",
    "Students created this week",
    "Students added this month",
    "Students modified last 7 days",
    "Confirmations today",
    "This week confirmations",
    "This month confirmations",
    "Last week confirmations",
    "Last month confirmations",
    "Submissions from April 2026",
    "March submissions",
    "This quarter submissions",
    "Last quarter submissions",
    "This year total submissions",
    "Last 2 days submissions",
    "Last 4 days interviews",
    "Interviews scheduled for today",
    "Tomorrow's interviews",
    "Show submissions after April 15",
    "Submissions before April 10",
    "Interviews in last 3 days",
    "Show last 60 days submissions",
    "Last 90 days interviews",
    "Submissions trend this month",
    "Daily submission count this week",
    "Weekly interview count this month",
    "Today's new students",
    "This week new students count",
    "How many submissions were made yesterday?",
    "How many interviews happened last week?",
    "Total submissions this month so far",
]

# ── BU-specific queries ──
BU_SPECIFIC_QUERIES = [
    "Show submissions for BU Abhijith Reddy",
    "Abhijith Reddy submissions this month",
    "Abhijith submissions today",
    "Abhijith BU this week submissions",
    "How many submissions for Abhijith this month?",
    "Show interviews for BU Abhijith",
    "Abhijith BU interviews this week",
    "Students under Abhijith Reddy",
    "How many students under Abhijith?",
    "Abhijith Reddy students with technology",
    "Show submissions for BU Adithya Reddy",
    "Adithya Reddy this month submissions",
    "Adithya BU interviews this week",
    "Students under Adithya Reddy Venna",
    "Adithya students count",
    "Show submissions for BU Vinay Singh",
    "Vinay Singh submissions this month",
    "Vinay Singh interviews last week",
    "Students under Vinay Singh",
    "Vinay BU performance this month",
    "Show submissions for BU Gulam Siddiqui",
    "Gulam Siddiqui this month submissions",
    "Gulam BU interviews this week",
    "Students under Gulam Siddiqui",
    "Gulam submissions count this month",
    "Show submissions for BU Divya Panguluri",
    "Divya Panguluri submissions today",
    "Divya BU this week submissions",
    "Students under Divya",
    "Divya Panguluri students with Java",
    "Show submissions for BU Kiran Reddy",
    "Kiran Reddy submissions this month",
    "Kiran BU interviews",
    "Students under Kiran Reddy",
    "Kiran Reddy Voorukonda students",
    "Show submissions for BU Ravi Mandala",
    "Ravi Mandala this month",
    "Ravi BU interviews this week",
    "Students under Ravi",
    "Show submissions for BU Prabhakar",
    "Prabhakar Kunreddy submissions",
    "Prabhakar BU interviews",
    "Students under Prabhakar",
    "Show submissions for BU Sriram",
    "Sriram submissions this month",
    "Sriram Anunthula BU students",
    "Show submissions for BU Manoj Prabhakar",
    "Manoj Prabhakar Daram submissions",
    "Manoj BU students list",
    "Show submissions for BU Prem Kumar",
    "Prem Kumar Malla this month",
    "Prem Kumar BU interviews",
    "Show submissions for BU Sudharshan",
    "Sudharshan Kumar submissions",
    "Sudharshan BU students",
    "Show submissions for BU Rakesh Ravula",
    "Rakesh Ravula this month submissions",
    "Rakesh BU interviews",
    "Show submissions for BU Satish Reddy",
    "Satish Reddy Mutthana submissions",
    "Satish BU students this month",
    "Abhijith Reddy last 7 days submissions",
    "Vinay Singh last 14 days interviews",
    "Divya Panguluri last week submissions",
    "Gulam Siddiqui this week interviews",
    "Kiran Reddy today submissions",
    "Adithya Reddy yesterday submissions",
    "Which BU has most submissions today?",
    "Which BU has most interviews this week?",
    "Top performing BU this month",
    "BU with least submissions this month",
    "BU comparison this month",
    "All BU submissions today",
    "All BU interviews this week",
    "BU wise count today",
    "BU wise submission count this month",
    "BU wise interview count this month",
    "Abhijith vs Adithya submissions this month",
    "Top 5 BUs by submissions this month",
    "Bottom 5 BUs by submissions this month",
    "BU with zero submissions this week",
    "BUs with no interviews today",
    "Show all BU managers",
    "List all BU names",
    "BU manager list with student count",
    "Abhijith Reddy students in market",
    "Vinay Singh active students",
    "Divya students with verbal confirmation",
    "Gulam Siddiqui confirmed students",
    "Students under Abhijith with Java",
    "Students under Vinay with DevOps",
    "Students under Divya with Python",
    "Abhijith BU students days in market",
    "Which BU has most students in market?",
    "BU wise student count",
    "BU wise active students",
]

# ── Aggregation and count queries ──
AGGREGATION_QUERIES = [
    "Submissions count BU wise this month",
    "Interviews count BU wise this week",
    "Student count by technology",
    "Student count by visa status",
    "Student count by marketing status",
    "Submissions by recruiter this month",
    "Submissions by offshore manager this month",
    "Top 10 BUs by submission count",
    "Top 5 technologies by student count",
    "Technology wise submission count this month",
    "Visa wise student distribution",
    "Status wise student count",
    "BU wise interviews this month",
    "BU wise confirmations this month",
    "Daily submission count this week",
    "BU wise submission count last week",
    "BU wise interview count last week",
    "Technology wise interview count",
    "Type wise interview breakdown this month",
    "Final status wise interview count",
    "BU wise student count in market",
    "Average days in market by technology",
    "Average days in market by BU",
    "Max days in market",
    "Students with more than 60 days in market count",
    "How many Java students are active?",
    "How many Python students in market?",
    "How many DevOps students total?",
    "How many H1B students active?",
    "How many OPT students in market?",
    "How many GC students?",
    "Total submissions this month",
    "Total interviews this month",
    "Total confirmations this month",
    "Total students in market",
    "Total active students",
    "Count of students per BU",
    "Count of submissions per client",
    "Top clients by submission count",
    "Which client has most submissions?",
    "Which technology has most students?",
    "Which visa type has most students?",
    "Submissions per day this week",
    "Interviews per day this month",
    "BU ranking by submissions this month",
    "BU ranking by interviews this month",
    "Recruiter performance this month",
    "Top recruiters by submission count",
    "Offshore manager performance this month",
    "BU wise submissions vs interviews this month",
    "How many confirmations this quarter?",
    "Quarterly submission count",
]

# ── Multi-object and comparison queries ──
MULTI_OBJECT_QUERIES = [
    "This month submissions, interviews and confirmations BU wise",
    "BU wise submissions and interviews this month",
    "Submissions and interviews comparison this week",
    "Which students have submissions but no interviews this month?",
    "Students with interviews but no confirmation",
    "BU performance - subs vs ints vs confirmations",
    "Students in market with zero submissions last 14 days",
    "Students with no interviews in 2 weeks",
    "Students with no submissions in 1 week",
    "Active students with no recent activity",
    "Dormant students - no submissions 30 days",
    "Students with most submissions this month",
    "Students with most interviews this month",
    "Which student has highest submission count?",
    "Submission to interview conversion rate by BU",
    "Interview to confirmation conversion this month",
    "BU efficiency - submissions per student",
    "Students confirmed this month with their BU",
    "Verbal confirmations with submission details",
    "Students who got confirmed after interviews",
    "New students who already have submissions",
    "Students added this month with interviews",
    "Fresh students with no submissions yet",
    "Students in market more than 90 days without interview",
    "Long waiting students by BU",
    "Stale students needing attention",
    "Students with multiple submissions this week",
    "Students with more than 5 submissions this month",
    "Students with more than 3 interviews this month",
    "Top performing students by submissions",
    "Monthly submission trend by BU",
    "Weekly submission growth",
    "BU comparison last month vs this month",
    "Which BU improved most this month?",
    "Declining BUs - less submissions than last month",
    "Students added vs confirmed this month",
    "Pipeline analysis - market to submission to interview",
    "Funnel analysis by BU",
    "Students under each offshore manager",
    "Offshore manager wise submissions",
    "Recruiter wise interviews scheduled",
    "Client wise submission breakdown",
    "Top clients this month",
    "New clients this month",
    "Technology demand - which tech has most submissions",
    "Technology with most interviews",
    "High rate submissions this month",
    "Average rate by technology",
    "Rate distribution by BU",
]

# ── Name-based lookups ──
NAME_BASED_QUERIES = [
    "Show details of Aravind Sunkara",
    "What is the status of Hemanth Reddy?",
    "How many submissions does Maruthi Pawan have?",
    "Interviews for Vyshnavi Boppana",
    "Which BU is Aravind Sunkara in?",
    "Details of Godala Rakesh Reddy",
    "Show Samhitha Reddy details",
    "Nithish Kumar submissions",
    "Divya Arige interview status",
    "Show Mani Kumar details",
    "Mohammed Numair submissions",
    "Pranavi Gantla information",
    "Arpana Reddy details",
    "Vishal Kamareddy status",
    "Show all details for Sai Vardhan",
    "Varun Teja submissions",
    "Cheruku Sathvik details",
    "Kirankumar Reddy status",
    "Find student named Kumar",
    "Search for Reddy students",
    "Who is Aravind?",
    "Show me Hemanth's technology",
    "What technology is Vyshnavi in?",
    "Which manager handles Aravind?",
    "Maruthi Pawan interview history",
    "Has Nithish got any interviews?",
    "Submissions by Divya Arige",
    "When was Mani Kumar's last submission?",
    "Show Pranavi's visa status",
    "How many days has Arpana been in market?",
    "All students named Reddy",
    "All students named Kumar",
    "Students with name Sai",
    "Find student Pawan",
    "Search for student Chinnamsetty",
    "Look up Ganesh",
    "Details about Boppana",
    "Status of student Sunkara",
    "Is Aravind still in market?",
    "When did Hemanth get confirmed?",
    "Show Maruthi's recent interviews",
    "Nithish Kumar recent submissions",
    "All activities for Vyshnavi",
    "Show complete profile of Aravind Sunkara",
    "Give me everything about Hemanth Reddy",
    "Full details Maruthi Pawan Avula",
    "Student profile Divya Arige",
    "Show personal details of Mohammed Numair",
    "When was Samhitha added?",
    "Godala Rakesh technology and visa",
]

# ── Report-style queries ──
REPORT_QUERIES = [
    "Send weekly report for BU Gulam Siddiqui",
    "Send weekly report for BU Abhijith Reddy",
    "Send weekly report for BU Vinay Singh",
    "Send weekly report for BU Divya Panguluri",
    "Send weekly report for BU Adithya Reddy",
    "Send weekly report for BU Kiran Reddy",
    "Send weekly report for BU Ravi Mandala",
    "Send weekly report for BU Prabhakar",
    "Send performance report for all BUs",
    "Weekly performance summary",
    "Monthly performance report",
    "BU performance dashboard",
    "Executive summary this month",
    "Weekly submission report",
    "Weekly interview report",
    "Monthly submission analysis",
    "Give me this week's summary",
    "What happened this week?",
    "This week's highlights",
    "Performance overview this month",
    "BU scorecard this month",
    "Submission scorecard this week",
    "Interview scorecard this month",
    "Top performers this month",
    "Underperforming BUs this month",
    "Weekly wrap-up report",
    "End of week summary",
    "Monday morning report",
    "Daily status report",
    "Today's performance summary",
    "Show me the dashboard data",
    "Give me KPIs for this month",
    "Key metrics this week",
    "Performance metrics all BUs",
    "Submission rate this month vs last month",
    "Send weekly report for BU Manoj Prabhakar",
    "Send weekly report for BU Prem Kumar",
    "Send weekly report for BU Sudharshan",
    "Weekly report BU Satish Reddy",
    "Generate report for Sriram BU",
]

# ── Edge cases and natural language variations ──
EDGE_CASES = [
    "subs today",
    "ints this week",
    "how many subs?",
    "today's ints",
    "show subs",
    "list ints",
    "give me subs bu wise",
    "submissions bu wise today",
    "interviews bu wise this week",
    "subs by bu this month",
    "ints by bu this week",
    "sub count",
    "int count",
    "student count",
    "total subs this month",
    "total ints this week",
    "confs this month",
    "confirmations",
    "verbal confirmations this month",
    "who got confirmed?",
    "latest confirmations",
    "recent confs",
    "show me data",
    "what's happening today?",
    "any submissions today?",
    "any interviews scheduled?",
    "anything new today?",
    "today update",
    "daily update",
    "status update",
    "quick summary",
    "brief overview",
    "show numbers",
    "give me stats",
    "performance today",
    "how are we doing?",
    "how's the team doing this month?",
    "are we on track?",
    "submissions?",
    "interviews?",
    "which bu is best?",
    "worst bu this month",
    "best performer",
    "worst performer",
    "lazy BUs",
    "active BUs",
    "top BU",
    "bottom BU",
    "abhijith subs",
    "vinay ints",
    "divya students",
    "gulam team",
    "kiran performance",
    "ravi submissions",
    "prabhakar interviews",
    "manoj subs this month",
    "java students count",
    "python devs",
    "dotnet count",
    "devops students how many",
    "h1b count",
    "opt students how many",
    "gc students list",
    "who all are in market?",
    "total in market",
    "market students",
    "bench strength",
    "how many on bench?",
    "exits this month",
    "who left this month?",
    "pulled out students",
    "not ready students",
    "pre marketing count",
    "project started this month",
    "new joiners",
    "freshers added",
    "team size",
    "total headcount",
    "submission rate today",
    "interview conversion",
    "hit rate",
    "success rate",
    "show everything for today",
    "complete today's data",
    "full report today",
    "all data this week",
    "everything this month",
    "give me all submissions with details",
    "detailed interview list this week",
    "comprehensive BU report",
    "complete breakdown this month",
]

# ── Complex analytical queries ──
COMPLEX_QUERIES = [
    "Which BU has the highest interview to confirmation ratio?",
    "Students in market more than 90 days what is blocking them?",
    "Compare this month vs last month submissions BU wise",
    "Which technology has highest placement rate?",
    "BUs with zero submissions this week who needs attention?",
    "Students with more than 5 submissions but no interview",
    "Average time from submission to interview by BU",
    "Which clients are we submitting to most?",
    "Dormant students no activity in 30 days",
    "New students added this month who already got submissions",
    "Show students who had interviews but got rejected last 30 days",
    "BU wise submissions vs last month comparison",
    "Which recruiters are submitting most this month?",
    "Technology wise submission to interview ratio",
    "Students waiting longest without any interview",
    "BU wise average days in market",
    "Which visa category gets most interviews?",
    "Top 3 technologies by demand this month",
    "Students with verbal confirmation this month by BU",
    "How many students moved from market to confirmation this month?",
    "Show me the submission funnel by BU",
    "Interview success rate by type",
    "Which interview type leads to most confirmations?",
    "Client interview vs vendor interview success rate",
    "Students with multiple rejections",
    "BU managers with declining submission numbers",
    "Growing BUs - more submissions each week",
    "Stagnant BUs - same submission count as last month",
    "Fresh students under 7 days with submissions already",
    "Students in market over 120 days still no placement",
    "Rate analysis - average rate by BU",
    "High value submissions - rate above 80",
    "Which BU gets highest rates?",
    "Technology demand trends",
    "Most active clients this month",
    "New clients we started submitting to",
    "Submission frequency per student",
    "Interview frequency per student",
    "BU capacity - students per manager",
    "Overloaded BUs - too many students per manager",
    "Which technology students have shortest time to placement?",
    "Best technology for quick placement",
    "Interview to offer ratio",
    "Offer acceptance rate by BU",
    "Students with gap in activity - last 2 weeks no submission",
    "BU wise fresh additions this month",
    "Experienced students still in market",
    "Students with both submissions and interviews this month",
    "Full cycle students - submission to interview to confirmation",
    "Breakdown of rejections by reason",
]

# ── Specific field/filter combinations ──
FIELD_COMBINATIONS = [
    "Java students in market under Abhijith",
    "Python students with H1B visa",
    "DevOps OPT students in market",
    "Data Engineering students with more than 30 days in market",
    ".NET students with verbal confirmation",
    "Salesforce students under Divya",
    "AWS students with interviews this month",
    "Azure students added recently",
    "Full Stack students in market more than 60 days",
    "SAP students count",
    "ServiceNow students in which BUs?",
    "Java H1B students under Vinay Singh",
    "Python GC students with submissions",
    "DevOps CPT students active",
    "Students with H4 EAD in market",
    "L2 visa students list",
    "STEM OPT Java students",
    "USC students with DevOps",
    "H1B transfer students",
    "Submissions for Java students this month",
    "Interviews for Python students this week",
    "DevOps submissions by BU today",
    "Data Engineering interviews this month",
    ".NET submissions last 7 days",
    "Salesforce student submissions today",
    "AWS interviews this week",
    "Which technology has most submissions today?",
    "Technology breakdown of this month's interviews",
    "Visa wise submission count this month",
    "H1B student submissions this month",
    "OPT student interviews this week",
    "GC students with confirmations",
    "Rate above 70 submissions this month",
    "Submissions with rate above 60 by BU",
    "High rate submissions for Java",
    "Average rate for Python submissions",
    "Top rated submissions this month",
    "Submissions with status interview scheduled",
    "Confirmed students technology breakdown",
    "Verbal confirmations by visa type",
    "Confirmations by technology this month",
    "BU wise confirmations with student details",
    "Recently confirmed students list",
    "Students confirmed in last 7 days",
    "This month confirmations with BU and technology",
    "Show confirmation trend this month",
    "Daily confirmations this month",
    "Weekly confirmations this quarter",
    "Offshore manager wise submission count",
    "Onsite lead wise interview count",
]

# ── Time-period variations ──
TIME_VARIATIONS = [
    "Submissions in last 1 day",
    "Submissions in last 2 days",
    "Submissions in last 3 days",
    "Submissions in last 5 days",
    "Submissions in last 7 days",
    "Submissions in last 10 days",
    "Submissions in last 14 days",
    "Submissions in last 21 days",
    "Submissions in last 30 days",
    "Submissions in last 45 days",
    "Submissions in last 60 days",
    "Submissions in last 90 days",
    "Interviews in last 1 day",
    "Interviews in last 3 days",
    "Interviews in last 5 days",
    "Interviews in last 7 days",
    "Interviews in last 10 days",
    "Interviews in last 14 days",
    "Interviews in last 21 days",
    "Interviews in last 30 days",
    "Students added in last 3 days",
    "Students added in last 7 days",
    "Students added in last 14 days",
    "Students added in last 30 days",
    "BU wise subs last 3 days",
    "BU wise subs last 7 days",
    "BU wise subs last 14 days",
    "BU wise subs last 30 days",
    "BU wise ints last 7 days",
    "BU wise ints last 14 days",
    "Abhijith last 3 days",
    "Vinay last 7 days submissions",
    "Divya last 14 days interviews",
    "Gulam last 30 days performance",
    "Submissions Monday to Friday this week",
    "This week so far submissions",
    "Month to date submissions",
    "Quarter to date interviews",
    "Year to date confirmations",
    "First half of this month submissions",
]

# ── Additional mixed queries to reach 1000+ ──
ADDITIONAL_QUERIES = [
    "Show me BU Abhijith Reddy complete report",
    "Full analysis of Vinay Singh BU",
    "Divya Panguluri BU health check",
    "Gulam Siddiqui team status",
    "Which students need attention?",
    "Students falling behind",
    "Students at risk of stagnation",
    "Pipeline health check",
    "Market readiness report",
    "Students ready for submission",
    "Students not getting interviews",
    "Why are submissions low this week?",
    "Interview pipeline status",
    "Confirmation pipeline",
    "Students close to confirmation",
    "Expected confirmations this month",
    "BU wise pipeline count",
    "Fresh leads this week",
    "New marketing students count",
    "Pre marketing to market conversion",
    "How long does it take to get first submission?",
    "Average time in market before first interview",
    "Fastest placements this month",
    "Quickest turnaround BU",
    "Slow moving students list",
    "Students stuck in market too long",
    "Action needed students",
    "Priority attention list",
    "High priority students",
    "Students with expired visa",
    "Visa expiring students",
    "H1B to GC students",
    "Status change this month",
    "Students who changed status recently",
    "Verbal to confirmed this month",
    "Market to verbal this month",
    "Exit students this month",
    "Why did students exit?",
    "Pulled out reasons",
    "Student attrition this month",
    "Retention rate by BU",
    "BU comparison chart data",
    "Submission velocity by BU",
    "Interview velocity this month",
    "Acceleration in submissions",
    "Deceleration in interviews",
    "Week over week growth",
    "Month over month trend",
    "Best day for submissions",
    "Peak submission days",
    "Slow days analysis",
    "Weekend submissions",
    "Weekday vs weekend submissions",
    "Morning vs evening submissions",
    "Show me the raw data",
    "Export submissions this month",
    "Give me data for Excel",
    "Download format data",
    "BU wise complete data dump",
    "All records this month",
    "Everything for Abhijith BU",
    "Complete Vinay Singh data",
    "All students all fields",
    "Full database export",
    "Maximum possible records",
    "Show 2000 submissions",
    "All interviews raw data",
    "Unfiltered student list",
    "No filter all data",
    "Top clients list",
    "Vendor analysis",
    "Prime vendor breakdown",
    "Which vendors perform best?",
    "Vendor submission count",
    "Client feedback on students",
    "Interview feedback summary",
    "Good feedback students",
    "Students with very good feedback",
    "Students with bad feedback",
    "Feedback trend this month",
    "Show me technology trends",
    "Emerging technologies",
    "Declining technology demand",
    "Hot skills this month",
    "Most in demand technology",
    "Technology with least students",
    "Oversupplied technologies",
    "Undersupplied technologies",
    "Technology gap analysis",
    "Skills market fit",
    "Show offshore managers list",
    "Offshore manager performance ranking",
    "Best offshore manager this month",
    "Offshore vs onsite manager comparison",
    "Recruiter efficiency report",
    "Top recruiter this month",
    "Recruiter submission rate",
    "Recruiter interview success rate",
    "Worst performing recruiter",
    "Recruiter improvement needed",
]

# ── More BU + date combos to push past 1000 ──
EXTRA_BU_DATE_QUERIES = [
    "Abhijith Reddy submissions last 3 days",
    "Abhijith Reddy interviews last 7 days",
    "Abhijith Reddy students added this month",
    "Abhijith Reddy confirmations this month",
    "Adithya Reddy submissions last 3 days",
    "Adithya Reddy interviews last 7 days",
    "Adithya Reddy students added this month",
    "Adithya Reddy confirmations this month",
    "Vinay Singh submissions last 3 days",
    "Vinay Singh interviews this month",
    "Vinay Singh students with Java",
    "Vinay Singh confirmations this quarter",
    "Divya Panguluri submissions last 3 days",
    "Divya Panguluri interviews last 14 days",
    "Divya Panguluri students in market count",
    "Divya Panguluri top students",
    "Gulam Siddiqui submissions last 3 days",
    "Gulam Siddiqui interviews last 14 days",
    "Gulam Siddiqui active students count",
    "Gulam Siddiqui students with Python",
    "Kiran Reddy submissions last 7 days",
    "Kiran Reddy interviews this month",
    "Kiran Reddy student technology breakdown",
    "Kiran Reddy dormant students",
    "Ravi Mandala submissions last 7 days",
    "Ravi Mandala interviews last 14 days",
    "Ravi Mandala students in market",
    "Ravi Mandala performance this week",
    "Prabhakar submissions last 7 days",
    "Prabhakar interviews this month",
    "Prabhakar student count",
    "Prabhakar BU submissions vs interviews",
    "Sriram submissions last 7 days",
    "Sriram interviews this month",
    "Sriram student list",
    "Sriram performance report",
    "Manoj Prabhakar submissions this week",
    "Manoj Prabhakar interviews last 14 days",
    "Manoj Prabhakar active students",
    "Manoj BU technology distribution",
    "Prem Kumar submissions this week",
    "Prem Kumar interviews this month",
    "Prem Kumar students status",
    "Prem Kumar BU report",
    "Sudharshan submissions this month",
    "Sudharshan interviews last 7 days",
    "Sudharshan active students",
    "Sudharshan BU performance",
    "Satish Reddy submissions this week",
    "Satish Reddy interviews last 14 days",
    "Satish Reddy student list with technology",
    "Satish Reddy BU daily submissions",
    "Rakesh Ravula submissions this month",
    "Rakesh Ravula interviews this week",
    "Rakesh Ravula students in market",
    "Rakesh Ravula performance this month",
    "Mukesh Ravula submissions this month",
    "Mukesh Ravula interviews this week",
    "Karthik Reddy submissions last 7 days",
    "Karthik Reddy interviews this month",
    "Venkata Sai submissions this month",
    "Venkata Sai interviews last 14 days",
    "Show all BU managers with their student count",
    "BU managers ranked by submissions this month",
    "BU managers ranked by interviews this month",
    "BU managers with no submissions this week",
    "BU managers with most confirmations",
    "Compare all BU managers this month",
    "BU managers active vs total students",
    "Which BU manager added most students this month?",
    "Show BU manager leaderboard",
    "BU wise submission trend last 30 days",
    "BU wise daily submissions this month",
    "BU wise weekly submissions this quarter",
    "Every BU today's submission count",
    "All BU interview count this week",
    "Complete BU breakdown this month submissions interviews confirmations",
    "Send daily report all BUs",
    "Abhijith team Java students count",
    "Vinay team DevOps students",
    "Divya team Python developers",
    "Gulam team .NET students",
    "Which BU has most Java students?",
    "Which BU has most DevOps students?",
    "Technology distribution across all BUs",
    "BU wise technology breakdown",
    "Visa distribution across BUs",
    "BU wise H1B student count",
    "BU wise OPT student count",
    "Which BU has most GC students?",
    "BU managers without any interviews this month",
    "Inactive BU managers",
    "Most improved BU this month",
    "BU needing most attention",
    "Bottom 3 BUs by activity",
    "Top 3 BUs by total activity",
    "BU wise average rate this month",
    "Which BU gets best rates?",
    "BU wise client distribution",
    "BU wise vendor distribution",
    "Abhijith vs Vinay vs Divya this month",
    "Top BU managers performance comparison",
    "BU ranking overall this month",
    "Daily submission chart data this month",
    "Submission heatmap data this month",
    "Interview calendar this week",
    "Upcoming interviews next 7 days",
    "Pending interview results",
    "Students awaiting interview feedback",
    "Re-scheduled interviews this month",
    "Cancelled interviews this month count",
    "No show interviews this month",
    "Interview completion rate by BU",
    "Successful interviews this month",
    "Failed interviews this month",
    "Interview pass rate by technology",
    "Which technology students ace interviews?",
    "Students with multiple interviews same week",
    "Students with back to back interviews",
    "Interview load per BU this week",
    "Interview scheduling efficiency",
    "Time between submission and interview",
    "Fastest submission to interview",
    "Slowest submission to interview",
    "Students waiting for interview after submission",
]

# ═══════════════════════════════════════════════════════════════════════
# COMBINE ALL QUESTIONS
# ═══════════════════════════════════════════════════════════════════════

ALL_CATEGORIES = [
    ("Simple Student", SIMPLE_STUDENT_QUERIES),
    ("Simple Submission", SIMPLE_SUBMISSION_QUERIES),
    ("Simple Interview", SIMPLE_INTERVIEW_QUERIES),
    ("Simple Job", SIMPLE_JOB_QUERIES),
    ("Simple Employee", SIMPLE_EMPLOYEE_QUERIES),
    ("Date Filtered", DATE_FILTERED_QUERIES),
    ("BU Specific", BU_SPECIFIC_QUERIES),
    ("Aggregation", AGGREGATION_QUERIES),
    ("Multi Object", MULTI_OBJECT_QUERIES),
    ("Name Based", NAME_BASED_QUERIES),
    ("Report Style", REPORT_QUERIES),
    ("Edge Cases", EDGE_CASES),
    ("Complex", COMPLEX_QUERIES),
    ("Field Combinations", FIELD_COMBINATIONS),
    ("Time Variations", TIME_VARIATIONS),
    ("Additional", ADDITIONAL_QUERIES),
    ("Extra BU Date", EXTRA_BU_DATE_QUERIES),
]

ALL_QUESTIONS = []
for cat, questions in ALL_CATEGORIES:
    for q in questions:
        ALL_QUESTIONS.append((cat, q))


# ═══════════════════════════════════════════════════════════════════════
# TEST RUNNER
# ═══════════════════════════════════════════════════════════════════════

def send_question(client, question, session_id=None):
    """Send a question to the chat API."""
    payload = {
        "session_id": session_id or str(uuid.uuid4()),
        "question": question,
    }
    try:
        response = client.post("/api/chat", json=payload)
        if response.status_code == 200:
            return {"ok": True, "body": response.json(), "status": 200}
        else:
            return {"ok": False, "error": f"HTTP {response.status_code}: {response.text[:200]}", "status": response.status_code}
    except Exception as e:
        return {"ok": False, "error": str(e), "status": 0}


def validate_response(result, question):
    """Check if response is valid."""
    if not result["ok"]:
        return False, result["error"]

    body = result["body"]
    if not body:
        return False, "Empty response body"

    answer = body.get("answer", "")
    if not answer:
        return False, "No answer in response"

    if len(answer) < 10:
        return False, f"Answer too short: '{answer}'"

    # Check for error indicators in the answer
    error_phrases = [
        "Schema not loaded",
        "Could not convert query",
        "I couldn't find data",
    ]
    for phrase in error_phrases:
        if phrase in answer:
            return False, f"Error in answer: {phrase}"

    return True, "OK"


def run_tests(questions=None, max_questions=None, category_filter=None):
    """Run test questions and report results."""
    headers = {}
    if AUTH_TOKEN:
        headers["Authorization"] = f"Bearer {AUTH_TOKEN}"

    client = httpx.Client(base_url=BASE_URL, timeout=120.0, headers=headers)

    # Filter questions
    test_set = questions or ALL_QUESTIONS
    if category_filter:
        test_set = [(c, q) for c, q in test_set if category_filter.lower() in c.lower()]
    if max_questions:
        test_set = test_set[:max_questions]

    print(f"\n{'='*70}")
    print(f"  CHAT API TEST SUITE - {len(test_set)} questions")
    print(f"  Server: {BASE_URL}")
    print(f"{'='*70}\n")

    passed = 0
    failed = 0
    errors = []

    for i, (category, question) in enumerate(test_set):
        result = send_question(client, question)
        is_valid, msg = validate_response(result, question)

        if is_valid:
            passed += 1
            if (i + 1) % 50 == 0:
                print(f"  Progress: {i+1}/{len(test_set)} ({passed} passed, {failed} failed)")
        else:
            failed += 1
            errors.append({
                "category": category,
                "question": question,
                "error": msg,
                "answer": result.get("body", {}).get("answer", "")[:200] if result.get("body") else "",
            })
            print(f"  X FAIL [{category}]: {question[:60]}")
            print(f"         Error: {msg[:100]}")

        # Small delay to not overwhelm the server
        time.sleep(0.5)

    # Summary
    print(f"\n{'='*70}")
    print(f"  RESULTS: {passed} PASSED | {failed} FAILED | {len(test_set)} TOTAL")
    print(f"  Pass rate: {passed/len(test_set)*100:.1f}%")
    print(f"{'='*70}")

    # Category breakdown
    print(f"\n  Category Breakdown:")
    cat_results = {}
    for cat, q in test_set:
        if cat not in cat_results:
            cat_results[cat] = {"total": 0, "failed": 0}
        cat_results[cat]["total"] += 1
    for e in errors:
        cat_results[e["category"]]["failed"] += 1

    for cat, stats in sorted(cat_results.items()):
        p = stats["total"] - stats["failed"]
        pct = p / stats["total"] * 100 if stats["total"] > 0 else 0
        status = "OK" if stats["failed"] == 0 else f"{stats['failed']} FAILED"
        print(f"    {cat:25s}: {p}/{stats['total']} ({pct:.0f}%) - {status}")

    # Detailed failures
    if errors:
        print(f"\n{'='*70}")
        print(f"  FAILED QUESTIONS ({len(errors)}):")
        print(f"{'='*70}")
        for i, e in enumerate(errors[:50], 1):
            print(f"\n  [{i}] [{e['category']}] {e['question']}")
            print(f"      Error: {e['error']}")
            if e['answer']:
                print(f"      Answer: {e['answer'][:150]}")

    # Save results to file
    results_file = os.path.join(os.path.dirname(__file__), "test_results.json")
    with open(results_file, "w") as f:
        json.dump({
            "total": len(test_set),
            "passed": passed,
            "failed": failed,
            "pass_rate": f"{passed/len(test_set)*100:.1f}%",
            "errors": errors,
        }, f, indent=2)
    print(f"\n  Results saved to: {results_file}")

    client.close()
    return passed, failed, errors


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Test chat questions against API")
    parser.add_argument("--max", type=int, help="Max questions to test")
    parser.add_argument("--category", type=str, help="Filter by category name")
    parser.add_argument("--url", type=str, help="API base URL")
    args = parser.parse_args()

    if args.url:
        BASE_URL = args.url

    # Print question count
    total = len(ALL_QUESTIONS)
    print(f"\nTotal questions available: {total}")
    for cat, qs in ALL_CATEGORIES:
        print(f"  {cat:25s}: {len(qs)}")

    passed, failed, errors = run_tests(
        max_questions=args.max,
        category_filter=args.category
    )

    sys.exit(0 if failed == 0 else 1)
