"""PDF report generation for chat answers."""
from datetime import datetime
from io import BytesIO
from app.timezone import now_cst

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
)
from reportlab.pdfgen import canvas as _canvas


BRAND = colors.HexColor("#e8734a")
TEXT_DARK = colors.HexColor("#1a1a22")
TEXT_MUTED = colors.HexColor("#5a5a6e")
BORDER = colors.HexColor("#d0d0d8")
SURFACE = colors.HexColor("#f5f5f7")


def _footer(canvas: _canvas.Canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(0.75 * inch, 0.5 * inch, "Generated by Fyxo Chat")
    canvas.drawRightString(7.75 * inch, 0.5 * inch, f"Page {doc.page}")
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(0.75 * inch, 0.7 * inch, 7.75 * inch, 0.7 * inch)
    canvas.restoreState()


def _clean(v):
    if v is None:
        return ""
    if isinstance(v, dict):
        return v.get("Name") or ""
    if isinstance(v, bool):
        return "Yes" if v else "No"
    return str(v)


def _strip_html(text):
    if not text:
        return ""
    import re
    text = re.sub(r"<br\s*/?>", "\n", text)
    text = re.sub(r"<[^>]+>", "", text)
    return text


def _escape(text):
    if text is None:
        return ""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def build_pdf(
    title: str,
    question: str,
    answer: str,
    soql: str | None,
    records: list | None,
    username: str = "user",
) -> bytes:
    """Render a report and return PDF bytes."""
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.9 * inch,
        bottomMargin=0.9 * inch,
        title=title or "Fyxo Data Report",
    )

    styles = getSampleStyleSheet()
    h_title = ParagraphStyle(
        "title", parent=styles["Title"], fontName="Helvetica-Bold",
        fontSize=20, textColor=BRAND, spaceAfter=4, alignment=0,
    )
    h_sub = ParagraphStyle(
        "sub", parent=styles["Normal"], fontName="Helvetica",
        fontSize=9, textColor=TEXT_MUTED, spaceAfter=18,
    )
    h_section = ParagraphStyle(
        "section", parent=styles["Heading3"], fontName="Helvetica-Bold",
        fontSize=11, textColor=TEXT_DARK, spaceBefore=14, spaceAfter=6,
    )
    p_body = ParagraphStyle(
        "body", parent=styles["Normal"], fontName="Helvetica",
        fontSize=10, textColor=TEXT_DARK, leading=14,
    )
    p_mono = ParagraphStyle(
        "mono", parent=styles["Code"], fontName="Courier",
        fontSize=9, textColor=TEXT_DARK, leading=12,
        backColor=SURFACE, borderColor=BORDER, borderWidth=0.5,
        borderPadding=8, leftIndent=0, rightIndent=0,
    )
    p_question = ParagraphStyle(
        "q", parent=p_body, fontName="Helvetica-Bold", textColor=TEXT_DARK,
    )

    story = []
    story.append(Paragraph("Fyxo Data Report", h_title))
    ts = now_cst().strftime("%B %d, %Y · %I:%M %p")
    story.append(Paragraph(f"Generated for <b>{_escape(username)}</b> · {ts}", h_sub))

    story.append(Paragraph("Question", h_section))
    story.append(Paragraph(_escape(question or "—"), p_question))

    story.append(Paragraph("Answer", h_section))
    answer_text = _strip_html(answer or "—")
    for para in answer_text.split("\n\n"):
        if para.strip():
            story.append(Paragraph(_escape(para).replace("\n", "<br/>"), p_body))
            story.append(Spacer(1, 4))

    if soql:
        story.append(Paragraph("SQL Query", h_section))
        story.append(Paragraph(_escape(soql), p_mono))

    if records:
        story.append(Paragraph(f"Data ({len(records):,} records)", h_section))
        cols = [k for k in records[0].keys() if k != "attributes"][:6]
        header = [Paragraph(f"<b>{_escape(c)}</b>", p_body) for c in cols]
        rows = [header]
        for r in records[:100]:
            row = []
            for c in cols:
                val = _clean(r.get(c))
                if len(val) > 60:
                    val = val[:57] + "..."
                row.append(Paragraph(_escape(val), p_body))
            rows.append(row)

        table = Table(rows, repeatRows=1, hAlign="LEFT")
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), SURFACE),
            ("TEXTCOLOR", (0, 0), (-1, 0), TEXT_DARK),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, SURFACE]),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(table)
        if len(records) > 100:
            story.append(Spacer(1, 6))
            story.append(Paragraph(
                f"<i>Showing first 100 of {len(records):,} records.</i>",
                ParagraphStyle("note", parent=p_body, textColor=TEXT_MUTED, fontSize=9),
            ))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()
