"""
SQLAlchemy models mirroring ALL Salesforce objects with exact field names.
Auto-generated from schema_cache.json
"""
from sqlalchemy import Column, String, Float, Integer, Boolean, Date, DateTime, Text
from sqlalchemy.orm import DeclarativeBase
from datetime import datetime


class Base(DeclarativeBase):
    pass


class Account(Base):
    __tablename__ = "Account"

    Id = Column(String(18), primary_key=True)
    MasterRecordId = Column(String(18))
    Name = Column(Text, index=True)
    Type = Column(Text)
    ParentId = Column(String(18))
    BillingStreet = Column(Text)
    BillingCity = Column(Text)
    BillingState = Column(Text)
    BillingPostalCode = Column(Text)
    BillingCountry = Column(Text)
    BillingLatitude = Column(Float)
    BillingLongitude = Column(Float)
    BillingGeocodeAccuracy = Column(Text)
    ShippingStreet = Column(Text)
    ShippingCity = Column(Text)
    ShippingState = Column(Text)
    ShippingPostalCode = Column(Text)
    ShippingCountry = Column(Text)
    ShippingLatitude = Column(Float)
    ShippingLongitude = Column(Float)
    ShippingGeocodeAccuracy = Column(Text)
    Phone = Column(Text)
    Fax = Column(Text)
    Website = Column(Text)
    PhotoUrl = Column(Text)
    Industry = Column(Text)
    AnnualRevenue = Column(Float)
    NumberOfEmployees = Column(Integer)
    Description = Column(Text)
    OwnerId = Column(String(18))
    CreatedDate = Column(DateTime)
    CreatedById = Column(String(18))
    LastModifiedDate = Column(DateTime)
    LastModifiedById = Column(String(18))
    LastActivityDate = Column(Date)
    LastViewedDate = Column(DateTime)
    LastReferencedDate = Column(DateTime)
    IsCustomerPortal = Column(Boolean)
    Jigsaw = Column(Text)
    JigsawCompanyId = Column(Text)
    AccountSource = Column(Text)
    SicDesc = Column(Text)
    Domain_Name__c = Column(Text)
    Account_Type__c = Column(Text)
    Cluster__c = Column(Text)
    synced_at = Column(DateTime, default=datetime.utcnow)


class Contact(Base):
    __tablename__ = "Contact"

    Id = Column(String(18), primary_key=True)
    MasterRecordId = Column(String(18))
    AccountId = Column(String(18))
    LastName = Column(Text)
    FirstName = Column(Text)
    Salutation = Column(Text)
    Name = Column(Text, index=True)
    OtherStreet = Column(Text)
    OtherCity = Column(Text)
    OtherState = Column(Text)
    OtherPostalCode = Column(Text)
    OtherCountry = Column(Text)
    OtherLatitude = Column(Float)
    OtherLongitude = Column(Float)
    OtherGeocodeAccuracy = Column(Text)
    MailingStreet = Column(Text)
    MailingCity = Column(Text)
    MailingState = Column(Text)
    MailingPostalCode = Column(Text)
    MailingCountry = Column(Text)
    MailingLatitude = Column(Float)
    MailingLongitude = Column(Float)
    MailingGeocodeAccuracy = Column(Text)
    Phone = Column(Text)
    Fax = Column(Text)
    MobilePhone = Column(Text)
    HomePhone = Column(Text)
    OtherPhone = Column(Text)
    AssistantPhone = Column(Text)
    ReportsToId = Column(String(18))
    Email = Column(Text)
    Title = Column(Text)
    Department = Column(Text)
    AssistantName = Column(Text)
    LeadSource = Column(Text)
    Birthdate = Column(Date)
    Description = Column(Text)
    OwnerId = Column(String(18))
    CreatedDate = Column(DateTime)
    CreatedById = Column(String(18))
    LastModifiedDate = Column(DateTime)
    LastModifiedById = Column(String(18))
    LastActivityDate = Column(Date)
    LastCURequestDate = Column(DateTime)
    LastCUUpdateDate = Column(DateTime)
    LastViewedDate = Column(DateTime)
    LastReferencedDate = Column(DateTime)
    EmailBouncedReason = Column(Text)
    EmailBouncedDate = Column(DateTime)
    IsEmailBounced = Column(Boolean)
    PhotoUrl = Column(Text)
    Jigsaw = Column(Text)
    JigsawContactId = Column(Text)
    IndividualId = Column(String(18))
    IsPriorityRecord = Column(Boolean)
    Lead__c = Column(String(18))
    Contact_Type__c = Column(Text)
    Ext__c = Column(Text)
    Domain_Formula__c = Column(Text)
    Contact_User_Type__c = Column(Text)
    synced_at = Column(DateTime, default=datetime.utcnow)


class SFUser(Base):
    __tablename__ = "User"

    Id = Column(String(18), primary_key=True)
    Username = Column(Text)
    LastName = Column(Text)
    FirstName = Column(Text)
    Name = Column(Text, index=True)
    CompanyName = Column(Text)
    Division = Column(Text)
    Department = Column(Text)
    Title = Column(Text)
    Street = Column(Text)
    City = Column(Text)
    State = Column(Text)
    PostalCode = Column(Text)
    Country = Column(Text)
    Latitude = Column(Float)
    Longitude = Column(Float)
    GeocodeAccuracy = Column(Text)
    Email = Column(Text)
    EmailPreferencesAutoBcc = Column(Boolean)
    EmailPreferencesAutoBccStayInTouch = Column(Boolean)
    EmailPreferencesStayInTouchReminder = Column(Boolean)
    SenderEmail = Column(Text)
    SenderName = Column(Text)
    Signature = Column(Text)
    StayInTouchSubject = Column(Text)
    StayInTouchSignature = Column(Text)
    StayInTouchNote = Column(Text)
    Phone = Column(Text)
    Fax = Column(Text)
    MobilePhone = Column(Text)
    Alias = Column(Text)
    CommunityNickname = Column(Text)
    BadgeText = Column(Text)
    IsActive = Column(Boolean)
    TimeZoneSidKey = Column(Text)
    UserRoleId = Column(String(18))
    LocaleSidKey = Column(Text)
    ReceivesInfoEmails = Column(Boolean)
    ReceivesAdminInfoEmails = Column(Boolean)
    EmailEncodingKey = Column(Text)
    ProfileId = Column(String(18))
    UserType = Column(Text)
    StartDay = Column(Text)
    EndDay = Column(Text)
    LanguageLocaleKey = Column(Text)
    EmployeeNumber = Column(Text)
    DelegatedApproverId = Column(String(18))
    ManagerId = Column(String(18))
    LastLoginDate = Column(DateTime)
    LastPasswordChangeDate = Column(DateTime)
    CreatedDate = Column(DateTime)
    CreatedById = Column(String(18))
    LastModifiedDate = Column(DateTime)
    LastModifiedById = Column(String(18))
    PasswordExpirationDate = Column(DateTime)
    NumberOfFailedLogins = Column(Integer)
    SuAccessExpirationDate = Column(Date)
    OfflineTrialExpirationDate = Column(DateTime)
    OfflinePdaTrialExpirationDate = Column(DateTime)
    UserPermissionsMarketingUser = Column(Boolean)
    UserPermissionsOfflineUser = Column(Boolean)
    UserPermissionsAvantgoUser = Column(Boolean)
    UserPermissionsCallCenterAutoLogin = Column(Boolean)
    UserPermissionsSFContentUser = Column(Boolean)
    UserPermissionsInteractionUser = Column(Boolean)
    UserPermissionsSupportUser = Column(Boolean)
    ForecastEnabled = Column(Boolean)
    UserPreferencesActivityRemindersPopup = Column(Boolean)
    UserPreferencesEventRemindersCheckboxDefault = Column(Boolean)
    UserPreferencesTaskRemindersCheckboxDefault = Column(Boolean)
    UserPreferencesReminderSoundOff = Column(Boolean)
    UserPreferencesDisableAllFeedsEmail = Column(Boolean)
    UserPreferencesDisableFollowersEmail = Column(Boolean)
    UserPreferencesDisableProfilePostEmail = Column(Boolean)
    UserPreferencesDisableChangeCommentEmail = Column(Boolean)
    UserPreferencesDisableLaterCommentEmail = Column(Boolean)
    UserPreferencesDisProfPostCommentEmail = Column(Boolean)
    UserPreferencesApexPagesDeveloperMode = Column(Boolean)
    UserPreferencesReceiveNoNotificationsAsApprover = Column(Boolean)
    UserPreferencesReceiveNotificationsAsDelegatedApprover = Column(Boolean)
    UserPreferencesHideCSNGetChatterMobileTask = Column(Boolean)
    UserPreferencesDisableMentionsPostEmail = Column(Boolean)
    UserPreferencesDisMentionsCommentEmail = Column(Boolean)
    UserPreferencesHideCSNDesktopTask = Column(Boolean)
    UserPreferencesHideChatterOnboardingSplash = Column(Boolean)
    UserPreferencesHideSecondChatterOnboardingSplash = Column(Boolean)
    UserPreferencesDisCommentAfterLikeEmail = Column(Boolean)
    UserPreferencesDisableLikeEmail = Column(Boolean)
    UserPreferencesSortFeedByComment = Column(Boolean)
    UserPreferencesDisableMessageEmail = Column(Boolean)
    UserPreferencesDisableBookmarkEmail = Column(Boolean)
    UserPreferencesDisableSharePostEmail = Column(Boolean)
    UserPreferencesEnableAutoSubForFeeds = Column(Boolean)
    UserPreferencesDisableFileShareNotificationsForApi = Column(Boolean)
    UserPreferencesShowTitleToExternalUsers = Column(Boolean)
    UserPreferencesShowManagerToExternalUsers = Column(Boolean)
    UserPreferencesShowEmailToExternalUsers = Column(Boolean)
    UserPreferencesShowWorkPhoneToExternalUsers = Column(Boolean)
    UserPreferencesShowMobilePhoneToExternalUsers = Column(Boolean)
    UserPreferencesShowFaxToExternalUsers = Column(Boolean)
    UserPreferencesShowStreetAddressToExternalUsers = Column(Boolean)
    UserPreferencesShowCityToExternalUsers = Column(Boolean)
    UserPreferencesShowStateToExternalUsers = Column(Boolean)
    UserPreferencesShowPostalCodeToExternalUsers = Column(Boolean)
    UserPreferencesShowCountryToExternalUsers = Column(Boolean)
    UserPreferencesShowProfilePicToGuestUsers = Column(Boolean)
    UserPreferencesShowTitleToGuestUsers = Column(Boolean)
    UserPreferencesShowCityToGuestUsers = Column(Boolean)
    UserPreferencesShowStateToGuestUsers = Column(Boolean)
    UserPreferencesShowPostalCodeToGuestUsers = Column(Boolean)
    UserPreferencesShowCountryToGuestUsers = Column(Boolean)
    UserPreferencesShowForecastingChangeSignals = Column(Boolean)
    UserPreferencesLiveAgentMiawSetupDeflection = Column(Boolean)
    UserPreferencesHideS1BrowserUI = Column(Boolean)
    UserPreferencesDisableEndorsementEmail = Column(Boolean)
    UserPreferencesPathAssistantCollapsed = Column(Boolean)
    UserPreferencesCacheDiagnostics = Column(Boolean)
    UserPreferencesShowEmailToGuestUsers = Column(Boolean)
    UserPreferencesShowManagerToGuestUsers = Column(Boolean)
    UserPreferencesShowWorkPhoneToGuestUsers = Column(Boolean)
    UserPreferencesShowMobilePhoneToGuestUsers = Column(Boolean)
    UserPreferencesShowFaxToGuestUsers = Column(Boolean)
    UserPreferencesShowStreetAddressToGuestUsers = Column(Boolean)
    UserPreferencesLightningExperiencePreferred = Column(Boolean)
    UserPreferencesPreviewLightning = Column(Boolean)
    UserPreferencesHideEndUserOnboardingAssistantModal = Column(Boolean)
    UserPreferencesHideLightningMigrationModal = Column(Boolean)
    UserPreferencesHideSfxWelcomeMat = Column(Boolean)
    UserPreferencesHideBiggerPhotoCallout = Column(Boolean)
    UserPreferencesGlobalNavBarWTShown = Column(Boolean)
    UserPreferencesGlobalNavGridMenuWTShown = Column(Boolean)
    UserPreferencesCreateLEXAppsWTShown = Column(Boolean)
    UserPreferencesFavoritesWTShown = Column(Boolean)
    UserPreferencesRecordHomeSectionCollapseWTShown = Column(Boolean)
    UserPreferencesRecordHomeReservedWTShown = Column(Boolean)
    UserPreferencesFavoritesShowTopFavorites = Column(Boolean)
    UserPreferencesExcludeMailAppAttachments = Column(Boolean)
    UserPreferencesSuppressTaskSFXReminders = Column(Boolean)
    UserPreferencesSuppressEventSFXReminders = Column(Boolean)
    UserPreferencesPreviewCustomTheme = Column(Boolean)
    UserPreferencesHasCelebrationBadge = Column(Boolean)
    UserPreferencesUserDebugModePref = Column(Boolean)
    UserPreferencesSRHOverrideActivities = Column(Boolean)
    UserPreferencesNewLightningReportRunPageEnabled = Column(Boolean)
    UserPreferencesReverseOpenActivitiesView = Column(Boolean)
    UserPreferencesHasSentWarningEmail = Column(Boolean)
    UserPreferencesHasSentWarningEmail238 = Column(Boolean)
    UserPreferencesHasSentWarningEmail240 = Column(Boolean)
    UserPreferencesNativeEmailClient = Column(Boolean)
    UserPreferencesHideBrowseProductRedirectConfirmation = Column(Boolean)
    UserPreferencesHideOnlineSalesAppWelcomeMat = Column(Boolean)
    UserPreferencesShowForecastingRoundedAmounts = Column(Boolean)
    ContactId = Column(String(18))
    AccountId = Column(String(18))
    CallCenterId = Column(String(18))
    Extension = Column(Text)
    PortalRole = Column(Text)
    IsPortalEnabled = Column(Boolean)
    FederationIdentifier = Column(Text)
    AboutMe = Column(Text)
    FullPhotoUrl = Column(Text)
    SmallPhotoUrl = Column(Text)
    IsExtIndicatorVisible = Column(Boolean)
    OutOfOfficeMessage = Column(Text)
    MediumPhotoUrl = Column(Text)
    DigestFrequency = Column(Text)
    DefaultGroupNotificationFrequency = Column(Text)
    LastViewedDate = Column(DateTime)
    LastReferencedDate = Column(DateTime)
    BannerPhotoUrl = Column(Text)
    SmallBannerPhotoUrl = Column(Text)
    MediumBannerPhotoUrl = Column(Text)
    IsProfilePhotoActive = Column(Boolean)
    IndividualId = Column(String(18))
    Company__c = Column(Text)
    Last_Login_Date__c = Column(DateTime)
    UserLiscence__c = Column(Text)
    synced_at = Column(DateTime, default=datetime.utcnow)


class SFReport(Base):
    __tablename__ = "Report"

    Id = Column(String(18), primary_key=True)
    OwnerId = Column(String(18))
    FolderName = Column(Text)
    CreatedDate = Column(DateTime)
    CreatedById = Column(String(18))
    LastModifiedDate = Column(DateTime)
    LastModifiedById = Column(String(18))
    Name = Column(Text, index=True)
    Description = Column(Text)
    DeveloperName = Column(Text)
    NamespacePrefix = Column(Text)
    LastRunDate = Column(DateTime)
    Format = Column(Text)
    LastViewedDate = Column(DateTime)
    LastReferencedDate = Column(DateTime)
    synced_at = Column(DateTime, default=datetime.utcnow)


class Student(Base):
    __tablename__ = "Student__c"

    Id = Column(String(18), primary_key=True)
    OwnerId = Column(String(18))
    Name = Column(Text, index=True)
    CreatedDate = Column(DateTime)
    CreatedById = Column(String(18))
    LastModifiedDate = Column(DateTime)
    LastModifiedById = Column(String(18))
    LastActivityDate = Column(Date)
    LastViewedDate = Column(DateTime)
    LastReferencedDate = Column(DateTime)
    Batch__c = Column(Text)
    Comments__c = Column(Text)
    DL_Expiry_Date__c = Column(Date)
    DL_Issue_Date__c = Column(Date)
    DL_Photo_Uploaded__c = Column(Text)
    DOB__c = Column(Date)
    District_In_India__c = Column(Text)
    EAD_Card_Number__c = Column(Text)
    Father_First_Name__c = Column(Text)
    Father_Last_Name__c = Column(Text)
    In_Market_Student_Count__c = Column(Float)
    Final_Marketing_Status__c = Column(Text)
    Folder_Sharing__c = Column(Text)
    Folder_in_Drive__c = Column(Text)
    GC_Back_Ref_Number__c = Column(Text)
    GC_Back_Verified__c = Column(Text)
    GC_Catogery__c = Column(Text)
    GC_Expiry_Date__c = Column(Date)
    GC_Issued_Date__c = Column(Date)
    GHID__c = Column(Float)
    Gender__c = Column(Text)
    Google_Voice_Number__c = Column(Text)
    Guest_House__c = Column(String(18))
    Has_Linkedin_Created__c = Column(Text)
    IS_DL_ID_CHANGED__c = Column(Text)
    India_Address_Line1__c = Column(Text)
    India_Address_Line2__c = Column(Text)
    Total_Count_not_Exit__c = Column(Float)
    Is_All_Docs_Reviewed_by_Manager__c = Column(Text)
    Is_DL_Ready__c = Column(Text)
    Is_DOC_Ready__c = Column(Text)
    Is_GC_Front_Verified__c = Column(Text)
    Is_Marketing_Sheet_Updated_by_Manager_Le__c = Column(Text)
    Is_Offer_Letter_Issued__c = Column(Text)
    LeadID__c = Column(String(18))
    Linkedin_Connection_Count__c = Column(Float)
    Linkedin_URL__c = Column(Text)
    MQ_Screening_By_Lead__c = Column(Text)
    MQ_Screening_By_Manager__c = Column(Text)
    MS_Sheet_Explanation__c = Column(Text)
    MS_Uploaded_By_Student__c = Column(Text)
    Marketing_Company__c = Column(String(18))
    Marketing_DOB__c = Column(Date)
    Marketing_Email__c = Column(Text)
    Marketing_End_Date__c = Column(Date)
    Marketing_Sheet_Screening_by_Lead__c = Column(Text)
    Marketing_Sheet_Screening_by_Manager__c = Column(Text)
    Marketing_Start_Date__c = Column(Date)
    Marketing_Visa_Status__c = Column(Text)
    Mother_First_Name__c = Column(Text)
    Mother_Last_Name__c = Column(Text)
    Offer_Issued_By_Name__c = Column(Text)
    Offer_Issued_By_Phone__c = Column(Text)
    Offer_Type__c = Column(Text)
    Onboarding_Company__c = Column(String(18))
    Onboarding_End_Date__c = Column(Date)
    Onboarding_Start_Date__c = Column(Date)
    Onboarding_Visa_Status__c = Column(Text)
    Otter_Final_Screening__c = Column(Text)
    Otter_Real_Time_Screeing_1__c = Column(Text)
    Otter_Real_Time_Screeing_2__c = Column(Text)
    Otter_Real_Time_Screeing_3__c = Column(Text)
    Otter_Real_Time_Screeing_4__c = Column(Text)
    PayRate__c = Column(Text)
    Passport_Number__c = Column(Text)
    Total_Interview_Amount__c = Column(Float)
    Personal_Email__c = Column(Text)
    Pin_In_India__c = Column(Text)
    PreMarketingStatus__c = Column(Text)
    Present_Client_Location__c = Column(Text)
    Recruiter__c = Column(String(18))
    Ref1__c = Column(Text)
    Ref2__c = Column(Text)
    Resume_Preparation__c = Column(Text)
    Resume_Verified_By_Lead__c = Column(Text)
    Resume_Verified_By_Manager__c = Column(Text)
    Review_comments__c = Column(Text)
    Shared_Drive_URL_To_Student__c = Column(Text)
    State_In_India__c = Column(Text)
    Student_First_Name__c = Column(Text)
    Student_GH_Arrival_Date__c = Column(Date)
    Student_GH_Departure_Date__c = Column(Date)
    Student_Last_Name__c = Column(Text)
    Student_Marketing_Status__c = Column(Text)
    Student_Personal_Mobile__c = Column(Text)
    Technology__c = Column(Text)
    Town_City_In_India__c = Column(Text)
    USCIS_Number__c = Column(Text)
    US_Emergency_Number__c = Column(Text)
    University__c = Column(Text)
    Visa_End_Date__c = Column(Date)
    Visa_Start_Date__c = Column(Date)
    Interviews_Count__c = Column(Float)
    Submission_Count__c = Column(Float)
    Total_Count__c = Column(Float)
    Paid_Offer_Start_Date__c = Column(Date)
    MarketingCompanyName__c = Column(Text)
    Month_Of_VC__c = Column(Text)
    Student_Full_Name__c = Column(Text)
    Manager__c = Column(String(18))
    Cluster_Account__c = Column(String(18))
    Submission_Count_URL__c = Column(Text)
    Interviews_Count_URL__c = Column(Text)
    Lead_Contact__c = Column(String(18))
    Manager_Contact__c = Column(String(18))
    Phone__c = Column(Text)
    Recruiter_Name__c = Column(Text)
    Offshore_Manager_Name__c = Column(Text)
    Students_Sitting_in_Office_GH_9AM_5PM__c = Column(Text)
    Basic_Knowledge_on_Subject__c = Column(Text)
    Communication_Skills__c = Column(Text)
    Dummy_Vendor_Call_to_Candidate__c = Column(Text)
    Recruiter_Screening__c = Column(Text)
    Prepared_Steps_need_to_Follow_Doc__c = Column(Text)
    Company_Mismatch__c = Column(Boolean)
    Recruiter_Contact__c = Column(String(18))
    OffShore_Manager_Contact__c = Column(String(18))
    OffShore_Floor_Manager_Contact__c = Column(String(18))
    Bill_Rate__c = Column(Float)
    Verbal_Conf_Count__c = Column(Float)
    Client_Name__c = Column(Text)
    Job_End_Date__c = Column(Date)
    Prime_Vendor_Name__c = Column(Text)
    Job_Start_Date__c = Column(Date)
    Vendor_Compnay_Name__c = Column(Text)
    Job_Location__c = Column(Text)
    Vendor_Person_Name__c = Column(Text)
    Vendor_Person_Email__c = Column(Text)
    Implementation_Partner__c = Column(Text)
    Interview_Date__c = Column(DateTime)
    Vendor_Person_Phone__c = Column(Text)
    Cluster_Contact__c = Column(String(18))
    Onsite_Lead_Name__c = Column(Text)
    Onsite_Manager_Name__c = Column(Text)
    Conf_Month__c = Column(Text)
    Marketing_Company_Name__c = Column(Text)
    Report_Students_Count__c = Column(Float)
    Cluster_Name__c = Column(Text)
    Verbal_Confirmation_Date__c = Column(Date)
    Job_Title__c = Column(Text)
    Days_in_Market_Business__c = Column(Float)
    Submissions__c = Column(Float)
    Interviews__c = Column(Float)
    Incentive_Amount__c = Column(Float)
    Recent_Interview_Date__c = Column(Date)
    Interview_Remarks__c = Column(Text)
    Recent_Past_Interview_Date__c = Column(Date)
    Students_Count_In_Market__c = Column(Float)
    Last_week_Submissions__c = Column(Float)
    Last_week_Interviews__c = Column(Float)
    RecentUpcoming_Interview_Datetime__c = Column(DateTime)
    RecentUpcoming_Interview_Date__c = Column(Date)
    Ceipal_Status__c = Column(Text)
    Last_Week_Interview_Count__c = Column(Float)
    Cluster__c = Column(Text)
    Verbal_or_Project_Started_Count__c = Column(Float)
    Lead_Bill_Rate__c = Column(Float)
    Project_Start_Month__c = Column(Text)
    Aug_2025_Submissions__c = Column(Float)
    Management__c = Column(Text)
    Old_Student__c = Column(String(18))
    Old_Manager_Name__c = Column(Text)
    Old_Student_Name__c = Column(Text)
    Old_Student_Phone__c = Column(Text)
    Student_ID__c = Column(Text)
    Project_Type__c = Column(Text)
    Conformation_Submission_ID__c = Column(String(18))
    Conformation_Interview_ID__c = Column(String(18))
    Father_Mobile_Number__c = Column(Text)
    India_Emergency_Contact_number__c = Column(Float)
    Parent_Mobile__c = Column(Text)
    Trigger_Check__c = Column(Text)
    Aug_2025_Interviews__c = Column(Float)
    June_2025_Interviews__c = Column(Float)
    June_2025_Submissions__c = Column(Float)
    July_2025_Interviews__c = Column(Float)
    July_2025_Submissions__c = Column(Float)
    Last_Submission_Date__c = Column(Date)
    Submissions_Count_From_Specific_Date__c = Column(Float)
    Vendor_Manager_Name__c = Column(Text)
    Onboarding_Cmpny__c = Column(Text)
    Last_End_To_End_Screening_Date__c = Column(Date)
    Availability__c = Column(Text)
    MS_Experience_Details_Screening__c = Column(Text)
    MS_Visa_Details_Screening__c = Column(Text)
    Resume_Verification__c = Column(Text)
    General_Marketing_Questions_Screening__c = Column(Text)
    Documents_Verification__c = Column(Text)
    Technical_Marketing_Questions_Screening__c = Column(Text)
    Otter_Screening__c = Column(Text)
    Daily_Tracker_Sheet_Review__c = Column(Text)
    Student_LinkedIn_Account_Review__c = Column(Text)
    Prime_Vendor_Database__c = Column(Text)
    Answering_To_Vendor__c = Column(Text)
    Reverse_Questions_To_Vendor__c = Column(Text)
    Recruiter_Department__c = Column(Text)
    Documents_Review__c = Column(Text)
    Resume_Review__c = Column(Text)
    Marketing_Sheet_Review__c = Column(Text)
    Month_Of_Paid_Offer__c = Column(Text)
    Vendor_Manager_Email__c = Column(Text)
    Recruiter_Start_Date__c = Column(Date)
    Supervisor_Name__c = Column(Text)
    Vendor_Manager_Phone__c = Column(Text)
    Domain_Name__c = Column(Text)
    Lead_Incentive_Applicable__c = Column(Boolean)
    Employee_Approval_Status__c = Column(Text)
    This_week_Interviews__c = Column(Float)
    This_week_Submissions__c = Column(Float)
    Lead_Incentive_Employee__c = Column(String(18))
    Sum_of_Amount_USD_Student__c = Column(Float)
    Reason_for_Exit__c = Column(Text)
    Active_Job_Count__c = Column(Float)
    synced_at = Column(DateTime, default=datetime.utcnow)


class Submission(Base):
    __tablename__ = "Submissions__c"

    Id = Column(String(18), primary_key=True)
    Name = Column(Text, index=True)
    CreatedDate = Column(DateTime)
    CreatedById = Column(String(18))
    LastModifiedDate = Column(DateTime)
    LastModifiedById = Column(String(18))
    LastActivityDate = Column(Date)
    LastViewedDate = Column(DateTime)
    LastReferencedDate = Column(DateTime)
    Student__c = Column(String(18))
    Client_Name__c = Column(Text)
    Implement_Company_Name__c = Column(Text)
    Prime_Vendor_Name__c = Column(Text)
    Rate__c = Column(Float)
    Recuter__c = Column(String(18))
    Submission_Date__c = Column(Date)
    Submission_Status__c = Column(Text)
    Vendor_Compnay_Name__c = Column(Text)
    Vendor_Person_Email__c = Column(Text)
    Vendor_Person_Name__c = Column(Text)
    Vendor_Person_Phone__c = Column(Text)
    Vendor_Company__c = Column(String(18))
    Vendor_Contact__c = Column(String(18))
    Ext__c = Column(Text)
    Last_3_Business_Days_Check__c = Column(Text)
    Job_Description__c = Column(Text)
    Onsite_Manager_Name__c = Column(Text)
    Offshore_Manager_Name__c = Column(Text)
    Recruiter_Name__c = Column(Text)
    Onsite_Lead_Name__c = Column(Text)
    Student_Name__c = Column(Text)
    Technology__c = Column(Text)
    Domain_Formula__c = Column(Text)
    Is_Today_Submission__c = Column(Float)
    BU_Name__c = Column(Text)
    Last_3_Business_Days__c = Column(Date)
    Vendor_Client_Student__c = Column(Text)
    Sub_Count__c = Column(Float)
    Is_Yesterday_s_Submission__c = Column(Boolean)
    Is_Last_Week_Sub__c = Column(Boolean)
    Comments__c = Column(Text)
    Last_Week_Business_Day_Check__c = Column(Text)
    synced_at = Column(DateTime, default=datetime.utcnow)


class Interview(Base):
    __tablename__ = "Interviews__c"

    Id = Column(String(18), primary_key=True)
    Name = Column(Text, index=True)
    CreatedDate = Column(DateTime)
    CreatedById = Column(String(18))
    LastModifiedDate = Column(DateTime)
    LastModifiedById = Column(String(18))
    LastActivityDate = Column(Date)
    LastViewedDate = Column(DateTime)
    LastReferencedDate = Column(DateTime)
    Student__c = Column(String(18))
    Amount__c = Column(Float)
    Duration__c = Column(Float)
    Interview_Date__c = Column(DateTime)
    Interview_Q_A__c = Column(Text)
    Month__c = Column(Text)
    Interviewer_Email__c = Column(Text)
    Interviewer_Name__c = Column(Text)
    Otter_Link__c = Column(Text)
    Submissions__c = Column(String(18))
    Support_First_Name__c = Column(Text)
    Support_Last_Name__c = Column(Text)
    Tech_Support__c = Column(String(18))
    Type__c = Column(Text)
    TechSupportName__c = Column(Text)
    Interview_End_Date_Time__c = Column(DateTime)
    Final_Status__c = Column(Text)
    Calender_Prefix__c = Column(Text)
    Lead_Manager_Joined__c = Column(Text)
    Student_Otter_Performance__c = Column(Text)
    Student_Technical_Explanation_Skill__c = Column(Text)
    Proxy_General_Issues__c = Column(Text)
    Any_Technical_Issues__c = Column(Text)
    Recruiter_Name__c = Column(Text)
    Offshore_Manager__c = Column(Text)
    Offshore_Floor_Manager__c = Column(Text)
    Onsite_Lead__c = Column(Text)
    Onsite_Manager__c = Column(Text)
    Cluster__c = Column(Text)
    Vendor_Company_Name__c = Column(Text)
    Vendor_Person_Name__c = Column(Text)
    Vendor_Person_Phone__c = Column(Text)
    Vendor_Email__c = Column(Text)
    Prime_Vendor_Name__c = Column(Text)
    Implementation_Partner__c = Column(Text)
    Client_Name__c = Column(Text)
    Bill_Rate__c = Column(Float)
    Student_Technology__c = Column(Text)
    Lead_Name__c = Column(Text)
    Project_Start_Date__c = Column(Date)
    Amount_INR__c = Column(Float)
    Verbal_Conf_Count__c = Column(Float)
    Interview_Date1__c = Column(Date)
    Paid__c = Column(Boolean)
    Int_Count__c = Column(Float)
    Manager_Tech__c = Column(Text)
    Interviews_Count__c = Column(Float)
    Final_Feedback__c = Column(Text)
    Job_Status__c = Column(Text)
    Verbal_Intw_Date__c = Column(Date)
    Paid_By__c = Column(Text)
    Is_Last_Week__c = Column(Boolean)
    synced_at = Column(DateTime, default=datetime.utcnow)


class Manager(Base):
    __tablename__ = "Manager__c"

    Id = Column(String(18), primary_key=True)
    OwnerId = Column(String(18))
    Name = Column(Text, index=True)
    CreatedDate = Column(DateTime)
    CreatedById = Column(String(18))
    LastModifiedDate = Column(DateTime)
    LastModifiedById = Column(String(18))
    LastActivityDate = Column(Date)
    LastViewedDate = Column(DateTime)
    LastReferencedDate = Column(DateTime)
    Cluster__c = Column(String(18))
    Email__c = Column(Text)
    Offshore_Floor_Manager__c = Column(String(18))
    Offshore_Location__c = Column(Text)
    Offshore_Manager__c = Column(String(18))
    Operation_Location__c = Column(Text)
    Organization__c = Column(String(18))
    User__c = Column(String(18))
    Cluster_Account__c = Column(String(18))
    Total_Expenses__c = Column(Float)
    Exit_Student_Count__c = Column(Float)
    Students_Count_In_Market__c = Column(Float)
    Project_Started_Count__c = Column(Float)
    Pre_Marketing_Student_Count__c = Column(Float)
    Total_Expenses_MIS__c = Column(Float)
    Each_Placement_Cost__c = Column(Float)
    Approval_Status__c = Column(Text)
    Visa__c = Column(Text)
    Type__c = Column(Text)
    Offshore_Google_Pin__c = Column(Text)
    Offshore_POC_Number__c = Column(Text)
    Website__c = Column(Text)
    Offshore_Location_Type__c = Column(Text)
    US_Office_Address__c = Column(Text)
    US_Office_Rent__c = Column(Float)
    Offshore_Office_Rent__c = Column(Float)
    Active__c = Column(Boolean)
    BU_Student_With_Job_Count__c = Column(Float)
    HR_Contact__c = Column(String(18))
    USA_HR_Phone__c = Column(Text)
    USA_HR_Email__c = Column(Text)
    Supervisor_Phone__c = Column(Text)
    Supervisor_Email__c = Column(Text)
    Docs_Upload_Drive_Link__c = Column(Text)
    Project_Status__c = Column(Text)
    Supervisor_Name__c = Column(Text)
    Organization_Name__c = Column(Text)
    HR_Name__c = Column(String(18))
    Offshore_Floor_Manager_Contact__c = Column(String(18))
    Manager_ID__c = Column(Text)
    US_Operation_CITY__c = Column(Text)
    US_Operation_State__c = Column(Text)
    Alias_Name__c = Column(Text)
    Old_Phone__c = Column(Float)
    New_Phone__c = Column(Text)
    Students_Count__c = Column(Float)
    In_Market_Students_Count__c = Column(Float)
    Verbal_Count__c = Column(Float)
    IN_JOB_Students_Count__c = Column(Float)
    India_HR__c = Column(Text)
    India_HR_Mail__c = Column(Text)
    synced_at = Column(DateTime, default=datetime.utcnow)


class Job(Base):
    __tablename__ = "Job__c"

    Id = Column(String(18), primary_key=True)
    OwnerId = Column(String(18))
    Name = Column(Text, index=True)
    CreatedDate = Column(DateTime)
    CreatedById = Column(String(18))
    LastModifiedDate = Column(DateTime)
    LastModifiedById = Column(String(18))
    LastActivityDate = Column(Date)
    LastViewedDate = Column(DateTime)
    LastReferencedDate = Column(DateTime)
    Active__c = Column(Boolean)
    Student_Name_Manager_Name__c = Column(Text)
    Month_SD__c = Column(Text)
    Month_ED__c = Column(Text)
    PayRate__c = Column(Text)
    Caluculated_Pay_Rate__c = Column(Float)
    Pay_Roll_Tax__c = Column(Float)
    Profit__c = Column(Float)
    Project_Type__c = Column(Text)
    Visa_Status__c = Column(Text)
    Company_Manager__c = Column(Text)
    Total_Interview_Amount__c = Column(Float)
    Month_Of_VC__c = Column(Text)
    Job_Title__c = Column(Text)
    Ceipal_Status__c = Column(Text)
    Triggered_Ceipal__c = Column(Boolean)
    Ceipal_Pay_Rate__c = Column(Float)
    Supervisor_Name__c = Column(Text)
    Hr_Contact__c = Column(String(18))
    Batch__c = Column(Text)
    Bill_Rate__c = Column(Float)
    Technology__c = Column(Text)
    Client_Name__c = Column(Text)
    Company__c = Column(Text)
    Implementation_Partner__c = Column(Text)
    Job_Location__c = Column(Text)
    PO_End_Dt__c = Column(Date)
    Verbal_Confirmation_Date__c = Column(Date)
    Payroll_Month__c = Column(Float)
    Supervisor_Name_Share__c = Column(Text)
    Percentage__c = Column(Float)
    Prime_Vendor_Name__c = Column(Text)
    Project_End_Date__c = Column(Date)
    Project_Start_Date__c = Column(Date)
    Recruiter__c = Column(Text)
    Share_With__c = Column(String(18))
    Student__c = Column(String(18))
    Vendor_Compnay_Name__c = Column(Text)
    Vendor_Person_Email__c = Column(Text)
    Vendor_Person_Name__c = Column(Text)
    Vendor_Person_Phone__c = Column(Text)
    synced_at = Column(DateTime, default=datetime.utcnow)


class Employee(Base):
    __tablename__ = "Employee__c"

    Id = Column(String(18), primary_key=True)
    OwnerId = Column(String(18))
    Name = Column(Text, index=True)
    CreatedDate = Column(DateTime)
    CreatedById = Column(String(18))
    LastModifiedDate = Column(DateTime)
    LastModifiedById = Column(String(18))
    LastActivityDate = Column(Date)
    LastViewedDate = Column(DateTime)
    LastReferencedDate = Column(DateTime)
    Deptment__c = Column(Text)
    Email__c = Column(Text)
    End_Dt__c = Column(Date)
    First_Name__c = Column(Text)
    Last_Name__c = Column(Text)
    OffShoreMgrID__c = Column(String(18))
    OffshoreFloorManager__c = Column(String(18))
    OffshoreLeadId__c = Column(String(18))
    Offshore_Location__c = Column(Text)
    Onshore_Manager__c = Column(String(18))
    Organization__c = Column(String(18))
    Phone__c = Column(Text)
    User__c = Column(String(18))
    Start_Dt__c = Column(Date)
    workPhoneNum__c = Column(Text)
    Full_Name__c = Column(Text)
    Keka_EMP_ID__c = Column(Text)
    Contact__c = Column(String(18))
    Cluster__c = Column(String(18))
    Offshore_Lead_Contact__c = Column(String(18))
    OffShore_Manager_Contact__c = Column(String(18))
    Offshore_Floor_Manager_Contact__c = Column(String(18))
    OnShore_Manager_Contact__c = Column(String(18))
    Approval_Status__c = Column(Text)
    Org_Account__c = Column(String(18))
    Cluster_Contact__c = Column(String(18))
    Latest_Verbal_Confirmation_Date__c = Column(Date)
    Total_Number_Of_Students__c = Column(Float)
    Confirmation_Count__c = Column(Float)
    Last_Login_Date__c = Column(Date)
    Cluster_Account__c = Column(String(18))
    Offshore_Manager_Lead_Name__c = Column(Text)
    Supervisor_Name__c = Column(Text)
    Organization_Name__c = Column(Text)
    Cluster_Name__c = Column(Text)
    Offshore_Floor_Manager__c = Column(Text)
    Employee_Duration__c = Column(Text)
    In_Market_Students_Count__c = Column(Float)
    Pre_Marketing_Student_Count__c = Column(Float)
    BU_Mail__c = Column(Text)
    India_HR_Mail__c = Column(Text)
    Offshore_Manager_Mail__c = Column(Text)
    BU_Name__c = Column(Text)
    synced_at = Column(DateTime, default=datetime.utcnow)


class BUPerformance(Base):
    __tablename__ = "BU_Performance__c"

    Id = Column(String(18), primary_key=True)
    Name = Column(Text, index=True)
    CreatedDate = Column(DateTime)
    CreatedById = Column(String(18))
    LastModifiedDate = Column(DateTime)
    LastModifiedById = Column(String(18))
    LastActivityDate = Column(Date)
    BU__c = Column(String(18))
    In_Market_Students_Count__c = Column(Float)
    Date__c = Column(Date)
    Submissions_Count__c = Column(Float)
    Interview_Count__c = Column(Float)
    submission__c = Column(Float)
    Target_Submissions__c = Column(Float)
    synced_at = Column(DateTime, default=datetime.utcnow)


class BS(Base):
    __tablename__ = "BS__c"

    Id = Column(String(18), primary_key=True)
    Name = Column(Text, index=True)
    CreatedDate = Column(DateTime)
    CreatedById = Column(String(18))
    LastModifiedDate = Column(DateTime)
    LastModifiedById = Column(String(18))
    LastActivityDate = Column(Date)
    LastViewedDate = Column(DateTime)
    LastReferencedDate = Column(DateTime)
    Student__c = Column(String(18))
    BU_Name__c = Column(Text)
    Vendor_Name__c = Column(Text)
    Bill_Rate__c = Column(Float)
    PayRate__c = Column(Text)
    Caluculated_Pay_Rate__c = Column(Float)
    Month__c = Column(Text)
    Year__c = Column(Text)
    Hours__c = Column(Float)
    Invoice_Amount__c = Column(Float)
    Actual_Salary__c = Column(Float)
    Salary_Paid__c = Column(Float)
    Insurance__c = Column(Float)
    H1fee__c = Column(Float)
    Other_Amounts__c = Column(Float)
    Pending_Amount__c = Column(Float)
    Payroll_Taxes__c = Column(Float)
    Gross_Profit__c = Column(Float)
    DOJ__c = Column(Date)
    Company_Name__c = Column(Text)
    Payment_Type__c = Column(Text)
    synced_at = Column(DateTime, default=datetime.utcnow)


class TechSupport(Base):
    __tablename__ = "Tech_Support__c"

    Id = Column(String(18), primary_key=True)
    OwnerId = Column(String(18))
    Name = Column(Text, index=True)
    CreatedDate = Column(DateTime)
    CreatedById = Column(String(18))
    LastModifiedDate = Column(DateTime)
    LastModifiedById = Column(String(18))
    LastActivityDate = Column(Date)
    LastViewedDate = Column(DateTime)
    LastReferencedDate = Column(DateTime)
    Amnt_Per_Call__c = Column(Float)
    Availability__c = Column(Text)
    Calendar_URL__c = Column(Text)
    Calls_Per_Day__c = Column(Float)
    Confirmtion_amount__c = Column(Float)
    Contact_Number2__c = Column(Text)
    Location__c = Column(Text)
    Name__c = Column(Text)
    OnSiteMgrID__c = Column(String(18))
    Payment_Type__c = Column(Text)
    Total_Amount__c = Column(Float)
    contact_Number1__c = Column(Text)
    Account_Details__c = Column(Text)
    Technology__c = Column(Text)
    Priority__c = Column(Text)
    Total_Interviews_Count__c = Column(Float)
    synced_at = Column(DateTime, default=datetime.utcnow)


class NewStudent(Base):
    __tablename__ = "New_Student__c"

    Id = Column(String(18), primary_key=True)
    OwnerId = Column(String(18))
    Name = Column(Text, index=True)
    CreatedDate = Column(DateTime)
    CreatedById = Column(String(18))
    LastModifiedDate = Column(DateTime)
    LastModifiedById = Column(String(18))
    LastActivityDate = Column(Date)
    LastViewedDate = Column(DateTime)
    LastReferencedDate = Column(DateTime)
    Manager__c = Column(String(18))
    Date_Of_Birth__c = Column(Date)
    Visa_Status__c = Column(Text)
    OPT_STEM_Start_Date__c = Column(Date)
    Interested_Tech__c = Column(Text)
    Phone__c = Column(Text)
    synced_at = Column(DateTime, default=datetime.utcnow)


class ManagerCard(Base):
    __tablename__ = "Manager_Card__c"

    Id = Column(String(18), primary_key=True)
    OwnerId = Column(String(18))
    Name = Column(Text, index=True)
    CreatedDate = Column(DateTime)
    CreatedById = Column(String(18))
    LastModifiedDate = Column(DateTime)
    LastModifiedById = Column(String(18))
    LastViewedDate = Column(DateTime)
    LastReferencedDate = Column(DateTime)
    Card__c = Column(String(18))
    Manager__c = Column(String(18))
    Source_Type__c = Column(Text)
    synced_at = Column(DateTime, default=datetime.utcnow)


class Cluster(Base):
    __tablename__ = "Cluster__c"

    Id = Column(String(18), primary_key=True)
    OwnerId = Column(String(18))
    Name = Column(Text, index=True)
    CreatedDate = Column(DateTime)
    CreatedById = Column(String(18))
    LastModifiedDate = Column(DateTime)
    LastModifiedById = Column(String(18))
    LastActivityDate = Column(Date)
    LastViewedDate = Column(DateTime)
    LastReferencedDate = Column(DateTime)
    Email__c = Column(Text)
    US_Number__c = Column(Text)
    India_Number__c = Column(Text)
    Cluster_Aliaz__c = Column(Text)
    Cluster_ID__c = Column(Text)
    IN_Job_Student_Count__c = Column(Float)
    synced_at = Column(DateTime, default=datetime.utcnow)


class Organization(Base):
    __tablename__ = "Organization__c"

    Id = Column(String(18), primary_key=True)
    OwnerId = Column(String(18))
    Name = Column(Text, index=True)
    RecordTypeId = Column(String(18))
    CreatedDate = Column(DateTime)
    CreatedById = Column(String(18))
    LastModifiedDate = Column(DateTime)
    LastModifiedById = Column(String(18))
    LastActivityDate = Column(Date)
    LastViewedDate = Column(DateTime)
    LastReferencedDate = Column(DateTime)
    ACCOUNT_NUMBER__c = Column(Text)
    Bank_Name__c = Column(Text)
    Bank_Phone_Number__c = Column(Text)
    Cluster__c = Column(String(18))
    Contract_Mgr__c = Column(String(18))
    Current_Address__c = Column(Text)
    DUNS_Number__c = Column(Text)
    Date_Incorporated__c = Column(Date)
    EIN__c = Column(Text)
    E_Verify_Number__c = Column(Text)
    File_Number__c = Column(Text)
    Major_Shareholder__c = Column(Text)
    Minor_Shareholder1_DIN_Number__c = Column(Text)
    Minor_Shareholder1__c = Column(Text)
    Minor_Shareholder1_s_CIN_NUMBER__c = Column(Text)
    Minor_Shareholder1_s_Date_of_Appointment__c = Column(Text)
    Minor_Shareholder2__c = Column(Text)
    Offler_Letter_format_Google_Drive_Link__c = Column(Text)
    Domain__c = Column(Text)
    OrgName__c = Column(Text)
    Owner_s_Mail_ID__c = Column(Text)
    Phone_Numbers__c = Column(Text)
    Registered_Address__c = Column(Text)
    Routing__c = Column(Text)
    Sales_Head__c = Column(String(18))
    Tax_Payer_Number__c = Column(Text)
    Web_File_Number__c = Column(Text)
    Website__c = Column(Text)
    Cluster_Account__c = Column(String(18))
    ORG_ID__c = Column(Text)
    Country_Incorporated__c = Column(Text)
    Current_Owner__c = Column(Text)
    Registered_Date__c = Column(Date)
    Registered_Owner__c = Column(Text)
    E_Verify_Login_ID__c = Column(Text)
    Swift_Code__c = Column(Text)
    IFSC_Code__c = Column(Text)
    Owner_Name__c = Column(Text)
    Cluster1__c = Column(Text)
    synced_at = Column(DateTime, default=datetime.utcnow)


class PayOff(Base):
    __tablename__ = "Pay_Off__c"

    Id = Column(String(18), primary_key=True)
    OwnerId = Column(String(18))
    Name = Column(Text, index=True)
    CreatedDate = Column(DateTime)
    CreatedById = Column(String(18))
    LastModifiedDate = Column(DateTime)
    LastModifiedById = Column(String(18))
    LastViewedDate = Column(DateTime)
    LastReferencedDate = Column(DateTime)
    Cluster__c = Column(Text)
    synced_at = Column(DateTime, default=datetime.utcnow)


# ─── App-specific models (not from Salesforce) ───


class User(Base):
    __tablename__ = "users"

    username = Column(String(100), primary_key=True)
    password_hash = Column(String(255), nullable=False)
    name = Column(String(255))
    role = Column(String(20), default="user")
    created_at = Column(DateTime, default=datetime.utcnow)


class ChatSession(Base):
    __tablename__ = "chat_sessions"

    id = Column(String(100), primary_key=True)
    username = Column(String(100), index=True, nullable=False)
    title = Column(String(255), default="New Chat")
    pinned = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class ChatMessage(Base):
    __tablename__ = "chat_messages"

    id = Column(String(100), primary_key=True)
    session_id = Column(String(100), index=True, nullable=False)
    role = Column(String(20), nullable=False)
    content = Column(Text)
    soql = Column(Text)
    data = Column(Text)
    ts = Column(DateTime, default=datetime.utcnow)


class AuditLog(Base):
    __tablename__ = "audit_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    username = Column(String(100), index=True)
    action = Column(String(100), index=True)
    details = Column(Text)
    ip_address = Column(String(50))


class SyncLog(Base):
    __tablename__ = "sync_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    object_name = Column(String(100), index=True)
    records_synced = Column(Integer)
    started_at = Column(DateTime)
    finished_at = Column(DateTime)
    status = Column(String(20))
    error = Column(Text)
